[project]
name = "altdate"
version = "0.0.1"
authors = ["don <don@0xbeef.org>"]

[dependencies]
docopt = "*"
rustc-serialize = "*"
time = "*"
chrono = "0.2"

[lib]
name = "altdate"
path = "src/altdate/mod.rs"
[[bin]]
name = "altdate"
path = "src/main.rs"
